### PR TITLE
Add header background #3

### PR DESCRIPTION
**Pull request by DinuBotan**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Added responsive background for header. Fixed issue #3

### CODE REVIEW

**Comment by NoahCardoza** [comment]
What about a banner of penguins?

**Comment by DinuBotan** [comment]
This is perfect haha 😂

**Comment by NoahCardoza** [comment]
I saw you added a new commit merging with main but it doesn't look like the new image was added to that commit. Just wanted to let you know in case there was any confusion.

**Comment by DinuBotan** [comment]
Should be changed now. For some reason I didn't make a feature branch for this and now everything was coming from 'main'..

**Comment by NoahCardoza** [comment]
Perfect!

**Pull request merged**
