### PR TITLE
Fellow separate page

### LINKED ISSUE #9: Profile page for each fellow
When you click on each fellows card, it sends you to a separate page which includes more detail such as:

- Description
- Favourite programming languages
- Interests outside of technology
- University

### PR DESCRIPTION
**Pull request by Pratyush1606**
Fixes #9 
Added a new `fellow.html` page to show the fellow details.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by shravani05** [comment]
@NoahCardoza can you please review this pr #28? Actually, we are unable to assign you as a reviewer.

**Comment by NoahCardoza** [comment]
Can you take a look at the merge conflicts? Sorry, just merged a lot of PRs 😬

**Comment by Pratyush1606** [comment]
Hey @NoahCardoza, I have resolved the conflict. Please have a look. Those were some end line conflicts.

**Comment by NoahCardoza** [comment]
Cool! Everything is looked good but do you think we can do something about these images. Some of them look a little squished:

image


Maybe try something like what was done here: https://github.com/MLH-Fellowship/pod-4.1.4-portfolio/blob/5a99e3ced47f25da7b86e9b91eef68dcdcc3c34a/_includes/description.html#L5

**Comment by Pratyush1606** [comment]
@NoahCardoza Now it looks fine. Please have a look!

**Comment by shravani05** [comment]
@NoahCardoza please have a look at the improved style.

pr

**Comment by NoahCardoza** [comment]
Looks great!

**Pull request merged**
