### PR TITLE
Update pod name and fellows data

### LINKED ISSUE #13: Add the pod!
Currently, then repository has members of the MLH team on it, but you should replace them with members of the pod.

You can update information in `_data/fellows.yml`

You should work on:
- [ ] Replacing the images
- [ ] Update the names and locations of each fellow
- [ ] Update the pod number inside of `_config.yml`

### PR DESCRIPTION
**Pull request by Pratyush1606**
Fixes #13 
* [x] Updated the pod name in `_config.yml`
* [x] Updated fellows data in the following format:
      - name: 
      - img: 
      - location: 
      - linkedin: 
      - github: 
      - resume: 
      - twitter:
      - description:
      - university: 
      - interests_outside_tech: 
      - fav_programming_language: 
* [x] Added fellow images

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by NoahCardoza** [comment]
Looking good so far! Since this PR is only about the data, don't worry about this but, we are going to have to do something about those images...

image

Do you guys want to take on that issue next? Maybe a carousel?

Also, feel free to add my info as well (I finally uploaded a picture to the channel on Discord).

**Comment by Pratyush1606** [comment]
@NoahCardoza I have added a script to remove unloaded images. Now it looks fine. Please have a look.

**Comment by Pratyush1606** [comment]
One more image is left.

**Comment by NoahCardoza** [comment]
> @NoahCardoza I have added a script to remove unloaded images. Now it looks fine. Please have a look.

Neat! I was actually referring to the fact that some of the images are different shapes. Sorry, I wasn't clear, I meant to add more detail but I must have become distracted.

While that bit of JavaScript is cool... since we'll have all the images we need when I merge the PR we shouldn't need it. But a must say that was a very creative solution 👍

**Comment by Pratyush1606** [comment]
@NoahCardoza Added the last image and removed the js script for not displaying unloaded images. Please have a look.

**Comment by NoahCardoza** [comment]
Looks great!

**Pull request merged**
