### PR TITLE
Update project page logo 

### LINKED ISSUE #5: Replace the MLH Fellowship logo with the MLH Prep logo
Screenshot 2021-09-30 at 18 38 57

When you go to the project page, it shows the MLH Fellowship logo at the top. It would be great to replace this with the Prep logo and make sure that's used throughout the website!

### PR DESCRIPTION
**Pull request by dans77777**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

**What the Pull Request is adding.**

Fix #5 by updating the Fellowship logo to the Prep logo on the project page.

### CODE REVIEW

**Comment by NoahCardoza** [comment]
Hey @dans77777, in the future it's best to keep short titles and include a longer description in the body of the issue. You can also add `fix/fixes #<issue-number>` somewhere in the body so that when the PR is merged, the issue will automatically be closed! How cool is that?

I'd suggest renaming the PR to something along the lines of: **"Update project page logo"**

And the body to something like:

Fix #5 by updating the Fellowship logo to the Prep logo on the project page.

**Comment by NoahCardoza** [comment]
Also, it's best not to change the Gemfile/.lock file unless you are adding a new dependency for the feature you are working on. It looks like you had to run some commands to get things to build correctly (which is perfect) but we can open a separate issue to address those troubles.

Please revert the change on the `Gemfile.lock` file you pushed and feel free to open an issue about updating some of the project's dependencies.

**Comment by NoahCardoza** [comment]
Any update on this PR?

**Comment by dans77777** [comment]
Hello,  there is no any updates from my side,  It's completed.
You can tell me if anything is missing.
Thank you.

**Comment by NoahCardoza** [comment]
According to GitHub, no files have been changed... maybe you didn't add/commit the new file?
image

**Comment by dans77777** [comment]
@NoahCardoza can you please check now? I have pushed my new changes and also attaching screenshot of output for your reference. Thank
Screenshot (12)

**Comment by NoahCardoza** [comment]
Perfect!

**Pull request merged**
